name: Automated Release
on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PNPM Environment
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js Runtime
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://npmjs.org'

      - name: Bypass Auth For Dependency Fetching
        run: echo "//registry.npmjs.org/:_authToken=" > .npmrc

      - name: Install Project Dependencies
        run: pnpm install

      - name: Compile Library Bundles
        run: pnpm build

      - name: Set Production NPM Auth Token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Publish Modulated Packages to NPM
        run: pnpm -r publish --no-git-checks
